### PR TITLE
Sync with pip

### PR DESCRIPTION
**Pull request by fpokryvk**
There are several minor changes and fixes. Please review per commit.

We should sync this with pip, since it diverges now.

### CODE REVIEW

**Comment by bittner** [comment]
Looks good to me!

Please fix the tests. I think it's the removed pretty-printing that make the HTML output different now.

Could you also try to make Flake8 pass? The complaints are most likely not from your changes, but it would be a shame to merge with a failing check. – Pylint complaints are harder to fix. We need to work on them separately, for sure.

**Comment by bittner** [comment]
> I will try to make the tests pass. It might take some time however.

It should be easy to fix them. I guess, you only need to collapse the [verbatim output in the feature files](https://github.com/behave-contrib/behave-html-formatter/blob/main/tests/acceptance/features/html-output.feature#L16-L26).

**Comment by fpokryvk** [comment]
If you would like to have commits reorganized (e.g. disable pretty HTML and fix the test in the same commit), I can easily do that (if we want that change easily reversible).

**Comment by fpokryvk** [comment]
I see some pypy3 fails, I have no idea what it is, did I break something by these changes?

**Comment by fpokryvk** [comment]
All green! Finally I found out the correct combination of pypy3.9, pypy-3.9 and pypy39 in config file :) Feel free to merge and create pip package. Thanks!

**Pull request merged**
